apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: clusters
  name: fulfillment-service
rules:
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
